theme: jekyll-theme-cayman
title: "Workshop: Introduction to Generative Drawing"
description: "This ICCC2020 workshop will introduce participants to generative computational drawing systems for art, music and design"
